pipeline {
	agent any

	stages {
	 	stage('Do something') {
	 		steps {
		 		sh "date"
		 		sh "ls -la"
		 		sh "echo 'feature branch'"
	 		}
	 	}
	}
	
	post {
    	success {
    		echo "Only when we haven't failed running the first stage"
    	}
    
    	failure {
    		echo "Only when we fail running the first stage."
    	}
  	}	
}
