pipeline {
	agent any

	stages {
	 	stage('Do something') {
	 		steps {
		 		sh "date"
		 		sh "ls -la"
		 		sh "sleep 20s"
		 		sh "echo 'first pipeline doin great'"
	 		}
	 	}
	}
	
	post {
    	success {
    		echo "This is success!"
    	}
    
    	failure {
    		echo "Failure on dev branch."
    	}
  	}	
}
